spring:
  datasource:
    url: jdbc:mysql://localhost:3306/halink_boot?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    timeout: 6000
    host: localhost
    port: 6379